export const badges = [
  { title: "🕋 Islam", value: "islam" },
  { title: "✅ Proofs", value: "proofs" },
  { title: "📖 Quran", value: "quran" },
  { title: "🌕 New to Islam", value: "new to islam" },
  { title: "💞 Marriage", value: "marriage" },
  { title: "🫂 Adab", value: "adab" },
  { title: "⛓️ Slavery", value: "slavery" },
  { title: "📿 Tawassul", value: "tawassul" },
  { title: "☝️ Aqeeda", value: "aqeeda" },
  // { title: "🌙 Islambackup", value: "islambackup" },
  { title: "🛡️ Defense", value: "defense" },
  { title: "🌹 Aisha RA", value: "aishara" },
  { title: "❤️ Prophet Muhammad ﷺ", value: "rasulallah" },
  { title: "⛪️ Christianity", value: "christianity" },
  { title: "⚛️ Atheism", value: "atheism" },
  // { title: "8thmane", value: "8thmane" },
  { title: "📚 Library", value: "library" },
  { title: "🗣️ Debate", value: "debate" },
  { title: "🏴 Salafi", value: "salafi" },
  { title: "🙏 Tazkia", value: "tazkia" },
];
